spring:
  artemis:
    port: ${JMS_PORT:61616}
    password: '12345'
    host: ${JMS_HOST:localhost}
    mode: native
    user: rod
  datasource:
    username: rod
    url: jdbc:postgresql://localhost:5432/businesstec
    password: '12345'
artemis:
  queue:
    fluxo: queue.fluxo
server:
  port: 8083

logging:
  level:
    org:
      springframework:
        ws:
          server:
            MessageTracing:
              received: TRACE
              sent: DEBUG
          client:
            MessageTracing:
              sent: DEBUG
              received: TRACE
        web: DEBUG


soap:
  default-uri: ${SOAP_DEFAULT_URI:http://192.91.254.104:8051/}
  package-wsdl: ${SOAP_PACKAGE_WSDL:br.com.businesstec.servicetotvs.wsdl}
  username: ${SOAP_USERNAME:integracaoJet}
  password: ${SOAP_PASSWORD:integr@jet#}
  realizar-consulta:
    path: ${REALIZAR_CONSULTA_PATH:wsConsultaSQL/IwsConsultaSQL}
    action: ${SOAP_ACTION_REALIZARCONSULTA:http://www.totvs.com/IwsConsultaSQL/RealizarConsultaSQL}
  save-record:
    path: ${REALIZAR_SAVE_RECORD_PATH:wsDataServer/IwsDataServer}
    action: ${SOAP_ACTION_SAVE_RECORD:http://www.totvs.com/IwsDataServer/SaveRecord}