spring:
  artemis:
    port: ${JMS_PORT:61616}
    password: '12345'
    host: ${JMS_HOST:localhost}
    mode: native
    user: rod
  datasource:
    username: rod
    url: jdbc:postgresql://localhost:5432/businesstec
    password: '12345'
artemis:
  queue:
    fluxo: queue.fluxo
server:
  port: 8081

soap:
  default-uri: ${SOAP_DEFAULT_URI:http://192.91.254.104:8051/wsConsultaSQL/IwsConsultaSQL}
  action: ${SOAP_ACTION:http://www.totvs.com/IwsConsultaSQL/RealizarConsultaSQL}
  package-wsdl: ${SOAP_PACKAGE_WSDL:br.com.businesstec.servicetotvs.wsdl}
  username: ${SOAP_USERNAME:integracaoJet}
  password: ${SOAP_PASSWORD:integr@jet#}